[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp", "--no-interaction"]
transport = "stdio"

[mcp_servers.NextjsTailwindAssistant]
transport = "http"
url = "https://server.smithery.ai/@CaullenOmdahl/nextjs-react-tailwind-assistant/mcp"
